//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public Answers()
        {
            this.Options = new HashSet<Options>();
            this.PatientsChoices = new HashSet<PatientsChoices>();
        }
    
        public int Id { get; set; }
        public int AnswerTypeId { get; set; }
        public int NumberOfPossibilities { get; set; }
        public int QuestionId { get; set; }
    
        public virtual AnswersTypes AnswersTypes { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual ICollection<Options> Options { get; set; }
        public virtual ICollection<PatientsChoices> PatientsChoices { get; set; }
    }
}
