//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsChoices
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int AnswerId { get; set; }
        public string Answer { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
