//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaires
    {
        public Questionnaires()
        {
            this.PatientsQuestionnaires = new HashSet<PatientsQuestionnaires>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PatientsQuestionnaires> PatientsQuestionnaires { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
