//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Answers = new HashSet<Answers>();
            this.Options = new HashSet<Options>();
        }
    
        public int Id { get; set; }
        public int QuestionnaireId { get; set; }
        public string Text { get; set; }
        public int NumberOfAnswers { get; set; }
    
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual ICollection<Options> Options { get; set; }
        public virtual Questionnaires Questionnaires { get; set; }
    }
}
