//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveysEntities : DbContext
    {
        public SurveysEntities()
            : base("name=SurveysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answers> Answers { get; set; }
        public DbSet<AnswersTypes> AnswersTypes { get; set; }
        public DbSet<Options> Options { get; set; }
        public DbSet<Patients> Patients { get; set; }
        public DbSet<PatientsChoices> PatientsChoices { get; set; }
        public DbSet<PatientsQuestionnaires> PatientsQuestionnaires { get; set; }
        public DbSet<Questionnaires> Questionnaires { get; set; }
        public DbSet<Questions> Questions { get; set; }
    }
}
